// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxzmomzfmqgesotdhaut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4em1vbXpmbXFnZXNvdGRoYXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzQ2MjUsImV4cCI6MjA2NDY1MDYyNX0.5-neVHEaiyM9WyLlH-6YK5gPko3nWEoOSBJLpSCPXsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);